INSERT INTO PRODUCT_PRICE (ID,PRODUCT,PRICE,DESCRIPTION,CREATE_TIME,MODIFY_TIME) VALUES(
1,'1001',10,'qe259@163.com',sysdate,sysdate);
INSERT INTO PRODUCT_PRICE (ID,PRODUCT,PRICE,DESCRIPTION,CREATE_TIME,MODIFY_TIME) VALUES(
2,'1002',20,'FINN1@163.com',sysdate,sysdate);
INSERT INTO PRODUCT_PRICE (ID,PRODUCT,PRICE,DESCRIPTION,CREATE_TIME,MODIFY_TIME) VALUES(
3,'1003',20,'JUNE2@163.com',sysdate,sysdate);
